### ISSUE TITLE
Support installation on Alpine

### ISSUE THREAD

**Issue by maxwellpeterson-wf** [dart-lang/dart_docker#50] opened 2019-09-26 15:54 UTC
It would be great to have dart docker images with smaller footprints for use in CI building and testing.

**Comment by kidac** [comment] 2019-11-05 05:40
I would also support this request. 
In combination with acqueduct and postgresql it would be a fast and lightweight combination for docker.

**Comment by jonasfj** [comment] 2019-11-11 10:12
Side note: The hard part here is probably configuring the Dart-SDK to compile with musl-libc.

**Comment by bsutton** [comment] 2020-07-10 04:03
I've done some work on making this work.

You can see my notes at the bottom of this page:

https://github.com/bsutton/dshell/wiki/Docker

The problem is that pub get is failing randomly on network requests. I'm guessing it might related to the glibc/musl-libc issue.

The rest of it (at least the bits I've tried) appear to be working.

**Comment by eldadfux** [comment] 2020-07-15 12:57
This would be a very useful feature, the official Dart image is about ~300MB right now while alpine images for other languages (PHP, Node, Python, Ruby) are all around ~25MB.

**Comment by Jasstkn** [comment] 2020-08-04 14:10
Any news about that? It's pretty inconvenient even using cache.

**Comment by subfuzion** [comment] 2020-10-30 00:55
In collaboration with @mit-mit and @mraleph, I created a slim image based on [scratch](https://hub.docker.com/_/scratch) called [dart-scratch](https://hub.docker.com/repository/docker/subfuzion/dart-scratch). It's available on Docker Hub at [subfuzion/dart-scratch](https://hub.docker.com/repository/docker/subfuzion/dart-scratch) for now.

The image weighs in a **4.97MB (2.05MB compressed on Docker Hub)** with only the essential system library support pulled in from Debian Buster (no need for Alpine or dealing with any glibc/musl-libc issues).

You can use the image to build JIT- or AOT-compiled apps in your image. See more at:

* GitHub [repo](https://github.com/subfuzion/dart-scratch)
* Medium [post](https://medium.com/google-cloud/build-slim-docker-images-for-dart-apps-ee98ea1d1cf7)
* Reddit [thread](https://www.reddit.com/r/dartlang/comments/ji4kix/create_minimal_docker_images_for_dart_using/)

**Disclaimer:** `subfuzion/dart-scratch` is not an official Google project. I haven't done a lot of testing so YMMV right now; I'm still iterating on it while I also work on creating a [buildpack](https://cloud.google.com/blog/products/containers-kubernetes/google-cloud-now-supports-buildpacks). At some point I'd like to see image available as an official image with the `dart:slim`. Feedback is welcome, but if you run into issues, please open them in the [repo](https://github.com/subfuzion/dart-scratch/issues), not here.

**Comment by mit-mit** [comment] 2021-06-02 12:26
Closing: We now support creating small serving images using the new Docker Official Image for Dart, see the "Using this image" section for how to build that:
https://hub.docker.com/_/dart

**Closed by mit-mit** 2021-06-02 12:26 UTC
Labels: enhancement
